export const surpriseMePrompts = [
  "A dragon riding a skateboard in a bustling city, cyberpunk style.",
  "A mermaid playing the saxophone in a jazz club, art deco.",
  "A griffin soaring above a medieval castle, in the style of a stained glass window.",
  "A unicorn frolicking in a field of lavender, impressionism.",
  "A centaur reading a book in a cozy library, digital art.",
  "A phoenix rising from the ashes, photorealistic.",
  "A mischievous goblin stealing a pie from a bakery window, cartoon style.",
  "A fairy riding a dragonfly, macro photography.",
  "A minotaur working as a barista, surrealism.",
  "A selkie basking in the sun on a rocky shore, impressionism.",
  "A dragon guarding a hidden treasure cave, fantasy art.",
  "A mermaid with a mermaid tail made of seaweed, surrealism.",
  "A griffin with wings made of feathers and metal, steampunk.",
  "A unicorn with a rainbow mane, digital art.",
  "A centaur playing chess with a human, surrealism.",
  "A phoenix made of fire, abstract art.",
  "A goblin blacksmith forging weapons, fantasy art.",
  "A fairy house hidden in a mushroom, macro photography.",
  "A minotaur as a gentle giant, caring for a lost child, fantasy art.",
  "A selkie transforming into a human on a moonlit beach, surrealism.",
  "A melting clock on a beach, in the style of Salvador Dalí.",
  "A giant eye floating in the clouds, surrealism.",
  "A teapot pouring out a waterfall, digital art.",
  "A forest made entirely of candy, photorealistic.",
  "A staircase leading into the sky, surrealism.",
  "A human head growing flowers, surrealism.",
  "A city built on the back of a giant whale, concept art.",
  "A floating island in the sky, fantasy art.",
  "A door leading to another dimension, surrealism.",
  "A person walking through a mirror and entering another world, digital art.",
  "A surreal landscape with melting buildings, digital art.",
  "A dream sequence with flying horses, surrealism.",
  "A teapot that pours out tea that turns into birds, surrealism.",
  "A forest where trees walk, digital art.",
  "A staircase that leads to the moon, surrealism.",
  "A human head made of gears, steampunk.",
  "A city built on the clouds, concept art.",
  "A floating island with a castle, fantasy art.",
  "A door that leads to a different time period, surrealism.",
  "A person dreaming they can fly, digital art.",
  "A cat piloting a spaceship, cyberpunk.",
  "A squirrel riding a unicycle, cartoon style.",
  "A dog wearing a tuxedo, photorealistic.",
  "A hummingbird with wings made of stained glass, digital art.",
  "A lion playing chess with a mouse, surrealism.",
  "A whale breaching in a storm, photorealistic.",
  "A butterfly with wings made of jewels, macro photography.",
  "A chameleon blending into a psychedelic background, digital art.",
  "A flock of birds flying in formation, impressionism.",
  "A tiger stalking its prey in the jungle, photorealistic.",
  "An elephant painting a self-portrait, surrealism.",
  "A monkey riding a bicycle, cartoon style.",
  "A dog playing the piano, digital art.",
  "A bird singing an opera, surrealism.",
  "A lion tamer taming a lion with a laser pointer, digital art.",
  "A whale singing a song, surrealism.",
  "A butterfly with wings that change color, digital art.",
  "A chameleon blending into a painting, surrealism.",
  "A flock of birds flying in formation, creating a unique shape, digital art.",
  "A tiger playing with a ball of yarn, cartoon style.",
  "A hamburger made entirely of vegetables, professional food photography.",
  "A pizza with toppings that look like planets, digital art.",
  "A giant ice cream sundae, photorealistic.",
  "A coffee cup that looks like a dragon, 3D render.",
  "A fruit salad that looks like a bouquet of flowers, digital art.",
  "A chocolate fountain flowing with liquid gold, surrealism.",
  "A cupcake with a tiny astronaut on top, macro photography.",
  "A stack of pancakes that look like a rainbow, digital art.",
  "A bowl of ramen with a miniature cityscape inside, surrealism.",
  "A pizza slice that looks like a piece of art, digital art.",
  "A hamburger that looks like a smiley face, digital art.",
  "A pizza with toppings that glow in the dark, surrealism.",
  "A giant ice cream cone with a cherry on top, photorealistic.",
  "A coffee cup that changes color when you drink from it, surrealism.",
  "A fruit salad made entirely of exotic fruits, digital art.",
  "A chocolate fountain that flows with different flavors of chocolate, surrealism.",
  "A cupcake with a tiny robot on top, digital art.",
  "A stack of pancakes that look like a staircase, surrealism.",
  "A bowl of ramen with a hidden message inside, digital art.",
  "A pizza slice that looks like a slice of the moon, surrealism.",
  "A robot dog playing fetch in a park, cyberpunk.",
  "A flying car hovering above a futuristic city, concept art.",
  "A cyborg exploring a cyberpunk city at night, neon lights.",
  "A VR headset that allows you to experience space travel, concept art.",
  "A robot chef cooking a gourmet meal, digital art.",
  "A holographic music concert, cyberpunk.",
  "A self-driving car navigating a busy highway, photorealistic.",
  "A robot bartender mixing a cocktail, digital art.",
  "A futuristic city built on the moon, concept art.",
  "A human brain connected to a computer, cyberpunk.",
  "A robot that can paint like a human, digital art.",
  "A flying car that transforms into a robot, concept art.",
  "A cyborg with superhuman abilities, digital art.",
  "A VR headset that allows you to travel through time, concept art.",
  "A robot that can play any musical instrument, digital art.",
  "A self-driving car that can fly, concept art.",
  "A cyborg with a robotic arm that can play chess, digital art.",
  "A VR headset that allows you to experience dreams, concept art.",
  "A robot that can create art, digital art.",
  "A self-driving car that can drive on water, concept art.",
  "A bustling street market in Marrakech, Morocco, photorealistic.",
  "A rainy day in London, with people hurrying under umbrellas, impressionism.",
  "A portrait of a young woman with thoughtful eyes, in the style of Rembrandt.",
  "A child laughing joyfully at the park, candid photography.",
  "A serene garden with a koi pond, Japanese aesthetic.",
  "A cozy living room with a fireplace on a snowy evening, hygge style.",
  "A delicious plate of pasta with fresh basil, close-up photography.",
  "A bustling coffee shop in Paris, with people enjoying their morning coffee, watercolor.",
  "A street musician playing guitar on a sunny afternoon, photorealistic.",
  "A dog playing fetch with its owner at the beach, golden hour.",
  "A person meditating in a peaceful forest, impressionism.",
  "A group of friends enjoying a picnic in a meadow, summer vibes.",
  "A portrait of an elderly woman with a kind smile, portrait photography.",
  "A child playing with a pile of colorful blocks, candid photography.",
  "A bustling city skyline at night, with neon lights reflecting on wet streets, cyberpunk.",
  "A person reading a book in a hammock under a shady tree, peaceful.",
  "A chef preparing a gourmet meal in a professional kitchen, documentary style.",
  "A person hiking in the mountains with breathtaking views, landscape photography.",
  "A cat curled up on a sunny windowsill, close-up photography.",
  "A mother and child sharing a tender moment, black and white photo.",
  "A majestic lion drinking from a watering hole, wildlife photography.",
  "A herd of elephants migrating across the savanna, photorealistic.",
  "A breathtaking underwater scene with colorful coral reefs and fish, underwater photography.",
  "A majestic redwood forest bathed in sunlight, landscape photography.",
  "A pod of dolphins leaping out of the water, high-speed photography.",
  "A breathtaking sunset over a vast ocean, landscape photography.",
  "A hummingbird feeding on a flower, macro photography.",
  "A wolf howling at the moon in a snowy landscape, wildlife photography.",
  "A majestic eagle soaring through the sky, aerial photography.",
  "A field of sunflowers swaying in the breeze, impressionism.",
  "A waterfall cascading down a rocky cliff, landscape photography.",
  "A school of fish swimming in a synchronized pattern, underwater photography.",
  "A spider spinning a web in the morning dew, macro photography.",
  "A family of monkeys playing in a jungle, wildlife photography.",
  "A polar bear hunting for seals on an ice floe, wildlife photography.",
  "A lush green forest with a hidden waterfall, landscape photography.",
  "A majestic mountain range with snow-capped peaks, landscape photography.",
  "A field of wildflowers blooming in the spring, impressionism.",
  "A baby panda cub playing with its mother, wildlife photography.",
  "A herd of deer grazing in a meadow, landscape photography.",
  "A futuristic city with flying cars and skyscrapers, concept art.",
  "A futuristic spaceship exploring a distant planet, space art.",
  "A virtual reality experience with stunning graphics, concept art.",
  "A futuristic robot assisting a human in a medical operation, science fiction.",
  "A data center with rows of powerful servers, technology photography.",
  "A holographic display showcasing a 3D model of a building, concept art.",
  "A person using a brain-computer interface to control a device, science fiction.",
  "A self-driving car navigating through a busy city, concept art.",
  "A futuristic drone delivering packages, concept art.",
  "A person using a smart home device to control their lights, technology photography.",
  "A team of scientists working in a high-tech laboratory, documentary style.",
  "A person using augmented reality glasses to explore a virtual world, concept art.",
  "A futuristic spacecraft landing on an alien planet, space art.",
  "A humanoid robot assisting a person with daily tasks, science fiction.",
  "A person using a wearable device to track their fitness, technology photography.",
  "A futuristic city with sustainable energy sources, concept art.",
  "A person using a virtual reality headset to attend a virtual conference, concept art.",
  "A team of engineers working on a new AI technology, documentary style.",
  "A futuristic medical device performing a non-invasive surgery, science fiction.",
  "A person using a smartphone to control their home appliances, technology photography.",
  "A dreamlike landscape with floating islands and surreal creatures, surrealism.",
  "A portrait of a person with their face made of gears, surrealism.",
  "A swirling vortex of colors and shapes, abstract art.",
  "A melting clock on a city street, in the style of Salvador Dalí.",
  "A person with a butterfly emerging from their chest, surrealism.",
  "A landscape where the sky and the ground are reversed, surrealism.",
  "A city made entirely of glass, surrealism.",
  "A portrait of a person with multiple eyes, surrealism.",
  "A dreamlike underwater world with bioluminescent creatures, surrealism.",
  "A person walking on air, surrealism.",
  "A giant eye watching over a city, surrealism.",
  "A staircase that leads to the moon, surrealism.",
  "A person with a head that is a clock, surrealism.",
  "A landscape where the trees are upside down, surrealism.",
  "A painting of a melting ice cream cone, surrealism.",
  "A person with a head made of clouds, surrealism.",
  "A city where buildings are made of water, surrealism.",
  "A portrait of a person with a thousand faces, surrealism.",
  "A landscape where the sky is filled with stars during the day, surrealism.",
  "A person with a head that is a television screen, surrealism.",
];